# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a9312259b4b08c84f87e07c84b3f0ffe26860b9d82eb1d5b7ed5690598ab2c91c79050e2fefdfc06ee20b26e68e63956731f237f8f8ae55c1f0cd66d68b0244

test:
  secret_key_base: 3886e9873466cf51e1d8b16d034a490605b6465826aff86f0d191e4ad225bc37b7737979103d5ebb72f2089662eaff38c156c4e21f3731c1aa0133ebc237ecef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
